"""empty message

Revision ID: 51fcc8cefcff
Revises: 3051372c77b2
Create Date: 2021-09-21 07:27:39.991300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51fcc8cefcff'
down_revision = '3051372c77b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website_lik', sa.String(length=120), nullable=True))
    op.drop_column('artist', 'website_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('artist', 'website_lik')
    # ### end Alembic commands ###
